### ISSUE TITLE
configurable pre-fetch count for rabbitMQ

### ISSUE THREAD

**Issue by EvaLok** [me-ventures/microservice-toolkit#10]

**Comment by MaikelH** [comment]
The prefetch count is currently set to 1 in the [rabbitmq event-bus](https://github.com/me-ventures/microservice-toolkit/blob/master/src/event-bus/rabbitmq.js#L69) module. 

The prefetch count is currently only used when using a named queue. The best thing is to add optional parameters to the `consumeShared` command. This also will make sure that everything is still backwards compatible.
