### ISSUE TITLE
add utility class

### ISSUE THREAD

**Issue by EvaLok** [me-ventures/microservice-toolkit#20]
starting simple..

```typescript
export namespace Utility {
    export function extend<T, U>(first: T, second: U): T & U {
        const result = {} as T & U;

        Object.keys(first).forEach((id: string) => {
            (result as any)[id] = (first as any)[id];
        });

        for (const id in second) {
            if (!result.hasOwnProperty(id)) {
                (result as any)[id] = (second as any)[id];
            }
        }
        return result;
    }
}
```

```javascript
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    var Utility;
    (function (Utility) {
        function extend(first, second) {
            var result = {};
            Object.keys(first).forEach(function (id) {
                result[id] = first[id];
            });
            for (var id in second) {
                if (!result.hasOwnProperty(id)) {
                    result[id] = second[id];
                }
            }
            return result;
        }
        Utility.extend = extend;
    })(Utility = exports.Utility || (exports.Utility = {}));
```

**Comment by EvaLok** [comment]
@MaikelH thinking about this again, a namespace is better than a class with static methods i think, similar to how there is `isNullOrUndefined` and so exported as functions in node's `util`

**Comment by EvaLok** [comment]
@MaikelH also, this by default has the second object not override preexisting properties of the first object; this seems unconventional (i would expect the second object's properties to override those of the first). maybe we could add an optional override or noOverride parameter to the extend function in order to address this

**Comment by MaikelH** [comment]
I like the idea of an namespace, makes a lot of sense. We can then use it the same way as `isNullOrUndefined` like you say.

Adding an extra property is good I think, by default we can set it to false.

**Comment by EvaLok** [comment]
so.. i actually started doing this (yarn is great btw), and as it turns out.. there is a good solution, that has `@types` with generics.. so.. think we're good :)

https://www.npmjs.com/package/deep-extend

```typescript
// Type definitions for open 0.4.1
// Project: https://github.com/unclechu/node-deep-extend
// Definitions by: rhysd <https://github.com/rhysd>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped


/*
 * Recursive object extending.
 */
declare function deepExtend<T, U>(target: T, source: U): T & U;
declare function deepExtend<T, U, V>(target: T, source1: U, source2: V): T & U & V;
declare function deepExtend<T, U, V, W>(target: T, source1: U, source2: V, source3: W): T & U & V & W;
declare function deepExtend(target: any, ...sources: any[]): any;
declare namespace deepExtend {}
export = deepExtend;
```

**Comment by MaikelH** [comment]
Nice, it had 9+ million downloads last month so it is probably decent 😏

**Comment by EvaLok** [comment]
also apparently yarn's lockfile is more reliable than npm's.. nice how everything sort of came together hehehe
