### ISSUE TITLE
Install optional handlers for  'uncaughtException' and 'unhandledRejection'

### ISSUE THREAD

**Issue by MaikelH** [me-ventures/microservice-toolkit#7]
`uncaughtException` and `unhandledRejection` are two events that would be useful  to have some metrics on. For example send some metrics that there was a exception.

To make it optional there can be a option in the logger config to enable or disable the eventhandlers.

**Comment by EvaLok** [comment]
this sounds good; i suppose we could give some pre-set handlers enabled via config that can then be overwritten at the user's discretion?

**Comment by MaikelH** [comment]
Yeah exactly, you can disable in them config and the user can use it is own handlers. Since it is an event, it is also possible to have multiple handlers.
